name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run test and coverage
      run: cargo llvm-cov --fail-under-lines 80